export const children = [
    {
       id: 1,
       name: "Айтакунову Аяту",
        image: "/images/child.png",
        age: "2 годика",
        need: "Нуждается в покупке химиотерапии",
        diagnosis: "Острый лимфобластный лейкоз Бишкек",
        necessary: 40000,
        collected: 30000,
        left: 10000,
    },
    {
        id: 2,
        name: "Айтакунову Аяту",
        image: "/images/child.png",
        age: "2 годика",
        need: "Нуждается в покупке химиотерапии",
        diagnosis: "Острый лимфобластный лейкоз Бишкек",
        necessary: 40000,
        collected: 30000,
        left: 10000,
    },{
        id: 3,
        name: "Айтакунову Аяту",
        image: "/images/child.png",
        age: "2 годика",
        need: "Нуждается в покупке химиотерапии",
        diagnosis: "Острый лимфобластный лейкоз Бишкек",
        necessary: 40000,
        collected: 30000,
        left: 10000,
    },{
        id: 4,
        name: "Айтакунову Аяту",
        image: "/images/child.png",
        age: "2 годика",
        need: "Нуждается в покупке химиотерапии",
        diagnosis: "Острый лимфобластный лейкоз Бишкек",
        necessary: 40000,
        collected: 30000,
        left: 10000,
    },{
        id: 5,
        name: "Айтакунову Аяту",
        image: "/images/child.png",
        age: "2 годика",
        need: "Нуждается в покупке химиотерапии",
        diagnosis: "Острый лимфобластный лейкоз Бишкек",
        necessary: 40000,
        collected: 30000,
        left: 10000,
    },{
        id: 6,
        name: "Айтакунову Аяту",
        image: "/images/child.png",
        age: "2 годика",
        need: "Нуждается в покупке химиотерапии",
        diagnosis: "Острый лимфобластный лейкоз Бишкек",
        necessary: 40000,
        collected: 30000,
        left: 10000,
    },{
        id: 7,
        name: "Айтакунову Аяту",
        image: "/images/child.png",
        age: "2 годика",
        need: "Нуждается в покупке химиотерапии",
        diagnosis: "Острый лимфобластный лейкоз Бишкек",
        necessary: 40000,
        collected: 30000,
        left: 10000,
    },
]